### PR TITLE
Fixed minor issues

### LINKED ISSUE #249: Adding options to refresh in pages
As of now, the pull-to-refresh option is pending in these pages:
- [x] All Workshops and Events
- [x] All Entities and Fests
- [x] Your Interests

### PR DESCRIPTION
**Pull request by nb9960**
- Fixed drawer behavior for home route (if current route is home route do nothing, else navigate to home route)

- Added shimmer effect on workshop detail page

- Changes textColor according to the theme

- Fixes #249 (added refresh option)

### CODE REVIEW

File: lib/pages/worshop_detail/workshopDetailPage.dart [hunk 1]
```diff
@@ -84,12 +110,21 @@ class _WorkshopDetailPage extends State<WorkshopDetailPage> {
...
               child: Text("No. Take Me Back."),
               onPressed: () => Navigator.of(context).pop(false),
             ),
             FlatButton(
               child: Text("Yup!"),
               onPressed: () => Navigator.of(context).pop(true),
+=======
+              child: Text("nope, let me rethink.."),
+              onPressed: () => Navigator.of(context).pop(false),
+>>>>>>> Fixed minor issues
```
Comment (mohit-mangal) [inline lib/pages/worshop_detail/workshopDetailPage.dart]: These lines should not be in code 😥 
Please remove such lines

Comment (mohit-mangal) [reply lib/pages/worshop_detail/workshopDetailPage.dart]: yes, you have fixed in later commits. Good !
